# Generated by Django 3.2.7 on 2021-11-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitconv', '0001_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUnit', models.CharField(max_length=200)),
                ('toUnit', models.CharField(max_length=200)),
                ('value', models.FloatField()),
            ],
        ),
    ]
