# Generated by Django 3.2.7 on 2021-11-14 19:47

# Generated by Django 3.2.7 on 2021-11-14 19:43

from django.db import migrations


def populate_db(apps, schema_editor):
    Convert = apps.get_model("unitconv","Convert")

    t_oz_conv = Convert(fromUnit = "t_oz", toUnit = "t_oz", value = 1)
    t_oz_conv.save()

    # T_conv = Convert(fromUnit = "T", toUnit = "t_oz", value = 32666.67189333)
    # T_conv.save()
    T_conv = Convert(fromUnit="T", toUnit="t_oz", value=29166.66835590)
    T_conv.save()

    # 0.032150746568628
    g_conv = Convert(fromUnit = "g", toUnit = "t_oz", value = 0.032150746568628)
    g_conv.save()

    kg_conv = Convert(fromUnit = "kg", toUnit = "t_oz", value = 32.150746568628)
    kg_conv.save()

    lb_conv = Convert(fromUnit = "lb", toUnit = "t_oz", value = 14.58333418)
    lb_conv.save()

    oz_conv = Convert(fromUnit = "oz", toUnit = "t_oz", value =0.91145839)
    oz_conv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0002_convert'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
